### ISSUE TITLE
nimma depends on jsonpath-plus <10

### ISSUE THREAD

**Issue by jacquesg** [P0lip/nimma#14]
See: https://github.com/advisories/GHSA-pppg-cpfq-h7wr

**Comment by P0lip** [comment]
Hey!
Nimma does not depend on jsonpath-plus at runtime - older versions used to, but that's been removed a few years ago.
However, it's indeed a dev dependency in this project since we run various compatibility [tests](https://github.com/P0lip/nimma/blob/master/src/__tests__/compatibility.test.mjs) and use jsonpath-plus to compare with.
As such, the vulnerability described does not really apply to Nimma.

FWIW, Nimma has only one runtime [dependency](https://github.com/P0lip/nimma/blob/master/package.json#L71) at the moment, namely [astring](https://www.npmjs.com/package/astring)

**Comment by jacquesg** [comment]
Indeed, apologies. The version used I was looking at is quite old, `0.2.2`.

**Comment by P0lip** [comment]
I could release 0.2.3 with an updated jsonpath-plus version if that helps.

**Comment by jacquesg** [comment]
That would definitely help and would be greatly appreciated!

**Comment by P0lip** [comment]
@jacquesg [0.2.3](https://www.npmjs.com/package/nimma/v/0.2.3) has been published

**Comment by jacquesg** [comment]
@P0lip Thank you! That really helps
