### ISSUE TITLE
Fallback does not work with indexOf

### ISSUE THREAD

**Issue by languitar** [P0lip/nimma#5]
I am using nimma in the context of spectral with the fallback option resorting to JSONPath Plus. I have a JSONPath expression that works well in JSONPath Plus. However, this expression is unusable in spectral because nimma raises an error instead of forwarding to the fallback implementation:

Here's the path I try to use:

```
$..properties[?(!@.nullable && (@parent.required || []).indexOf(@property) == -1)]
```

And here's the error I get in spectral:

```
❯ spectral --version
6.4.1

❯ spectral lint openapi-spec.yaml -r .spectral.yaml -v
Found 72 rules (61 enabled)
Linting /xxx/openapi-spec.yaml
Error running Spectral!
Error #1: (scope.sandbox.parentValue.required || []).indexOf is not a function
          at indexOf(@property) …  …js/core/index.js:66  _rollupPluginBabelH…
          at eval                  …js/core/index.js:66  _rollupPluginBabelH…
          at _traverseBody         …time/traverse.js:13  cb(scope);          
          at _traverse             …time/traverse.js:41  _traverseBody(key, …
          at _traverseBody         …time/traverse.js:17  _traverse(value, sc…
```

**Comment by NickHeap2** [comment]
@languitar I have a similar issue with our rules that worked on 22nd June then stopped working on 12th July when we updated dependencies.

**Comment by P0lip** [comment]
This isn't an issue with `nimma`. The issue here is that `scope.sandbox.parentValue.required` is presumably some truthy value that isn't an array.
Consider using the following `'$..properties[?(!@.nullable && @parent.required && @parent.required.indexOf && @parent.required.indexOf(@property) == -1)]`

---
On a side note - I'd really refrain from the usage of `@parent` and a-like as they are non-standard and won't work with other implementations.
